#pragma kernel CSMain

struct Vert
{
	float4 position;
	float3 normal;
};

RWStructuredBuffer<Vert> _Buffer;

int _Width, _Height, _Depth;

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	int idx = id.x + id.y * _Width + id.z * _Width * _Height;
	
	for (int i = 0; i < 5; i++)
	{
		for (int j = 0; j < 3; j++)
		{
			Vert vert;
			vert.position = float4(-1,-1,-1,-1);
			vert.normal = float3(0,0,0);

			_Buffer[idx * 15 + (3 * i + j)] = vert;
		}
	}
}